site_name: DuckPGQ Documentation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append: ["_snippets/_report_issue.md"]
      base_path: ["docs"]
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - DuckPGQ: index.md
  - Documentation:
    - SQL/PGQ: documentation/sql_pgq.md
    - Graph Functions: documentation/graph_functions.md
    - Property Graph: documentation/property_graph.md
    - Loading DuckPGQ: documentation/loading.md
    - Building DuckPGQ: documentation/building_duckpgq.md
    - Contribution & Setup Guide: documentation/contribution_guide.md
  - Resources:
    - Publications: resources/publications.md

theme:
  name: material
  logo: assets/duckpgq-logo.png
  favicon: assets/duckpgq-logo-circular.png
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/cwida/duckpgq-extension
repo_name: DuckPGQ

extra:
  generator: false
  footer:
    text: |
      <a href="https://github.com/cwida/duckpgq-extension/issues/new?title=Issue%20found%20in%20documentation&body=Please%20describe%20the%20problem%20and%20include%20a%20URL%20of%20the%20page%20if%20possible." 
         title="Create GitHub issue" target="_blank">Report a Documentation Issue</a>

extra_javascript:
  - https://kit.fontawesome.com/a076d05399.js

