site_name: DuckPGQ
site_url: https://duckpgq.org
site_description: DuckDB extension that adds support for SQL/PGQ and graph algorithms


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append: ["_snippets/_report_issue.md"]
      base_path: ["docs"]
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - pymdownx.tabbed:
      alternate_style: true 

nav:
  - Home: index.md
  - Documentation:
    - SQL/PGQ: documentation/sql_pgq.md
    - Graph Functions: documentation/graph_functions.md
    - Property Graph: documentation/property_graph.md
    - Loading DuckPGQ: documentation/loading.md
    - Building DuckPGQ: documentation/building_duckpgq.md
    - Contribution & Setup Guide: documentation/contribution_guide.md
  - Resources:
    - Publications: resources/publications.md

theme:
  name: material
  logo: assets/duckpgq-logo-circular.png
  favicon: assets/duckpgq-logo-head.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - announce.dismiss
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/cwida/duckpgq-extension
repo_name: DuckPGQ

plugins:
  - git-authors:
      show_email_address: true
      href: "https://github.com/{name}"
      sort_authors_by: name
      exclude:
        - index.md
  - git-revision-date-localized:
      enable_creation_date: true
      type: date  # Displays full date and time
      fallback_to_build_date: true
      exclude:
        - index.md
  - search

extra:
  generator: false

extra_javascript:
  - https://kit.fontawesome.com/a076d05399.js
  - javascripts/install-environment.js

extra_css:
  - stylesheets/custom_css.css
