site_name: DuckPGQ Documentation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - DuckPGQ: index.md
  - Documentation:
    - SQL/PGQ: documentation/sql_pgq.md
    - Graph Functions: documentation/graph_functions.md
    - Property Graph: documentation/property_graph.md
    - Loading DuckPGQ: documentation/loading.md
    - Building DuckPGQ: documentation/building_duckpgq.md
    - Contribution & Setup Guide: documentation/contribution_guide.md
  - Resources:
    - Publications: resources/publications.md

theme:
  name: material
  logo: assets/duckpgq-logo.png
  favicon: assets/duckpgq-logo-circular.png
  custom_dir: overrides
  features:
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/cwida/duckpgq-extension
repo_name: DuckPGQ

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/8X95XHhQB7

extra_javascript:
  - https://kit.fontawesome.com/a076d05399.js

